name: Android CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  FCLTeamBuild:
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false
    env:
      FCL_KEYSTORE_PASSWORD: ${{ secrets.FCL_KEYSTORE_PASSWORD }}
      CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
      OAUTH_API_KEY: ${{ secrets.OAUTH_API_KEY }}
    name: Build for ${{matrix.arch}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build ${{matrix.arch}} .apk
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease -Darch=${{matrix.arch}}

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app-${{matrix.arch}}
          path: FCL/build/outputs/apk/release/*
        #  retention-days: 1

#only for fork
  DebugBuild:
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false
    env:
      FCL_KEYSTORE_PASSWORD: ${{ secrets.FCL_KEYSTORE_PASSWORD }}
      CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
      OAUTH_API_KEY: ${{ secrets.OAUTH_API_KEY }}
    name: Build for ${{matrix.arch}} Debug
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build debug apk
        run: |
          chmod +x gradlew
          ./gradlew assemblefordebug -Darch=all

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-all
          path: FCL/build/outputs/apk/fordebug/*
